
<div class="page-header">
    <h1><?php echo $this->titulo.  "-" . $this->resultado;?></h1>
</div>

<table class="table" style="width:700px;">
    <tbody>
        <tr>
            <td>id</td><td>nombre</td><td>apellido</td><td>correo</td><td>nombre usuario</td>
        </tr>
             <?php foreach ($this->usuario as $usuario): ?>
            <tr style="background-color:<?php echo $this->cycle(array("#F0F0F0","#FFFFFF"))->next()?>">
                <td><?php echo $usuario->getId() ?></td>
                <td><?php echo $usuario->getNombre() ?></td>
                <td><?php echo $usuario->getApellido() ?></td>
                <td><?php echo $usuario->getCorreo() ?></td>
                <td><?php echo $usuario->getUserName() ?></td>
                <td>
                    
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
    <?php
    $this->cycle()->assign(array("#F0F0F0", "#FFFFFF"));
    $this->cycle()->prev();
    ?>
</table>
</form>