<?= $this->doctype() ?>

<html lang="en">
    <head>
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-2.2.4.min.js'))
        ?>
    </head>
    <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
              <img src="<?= $this->basePath('img/zf-logo.png') ?>" alt="Zend Framework <?= \Application\Module::VERSION ?>"/>&nbsp;Skeleton Application
          </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="<?= $this->url('home') ?>">Home</a></li>
            <li><a href="<?= $this->url('usuario') ?>">Usuario</a></li>
            <li><a href="#contacto">Contacto</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="">Registrarse</a></li>
            <li><a href="">Login</a></li>
            <li class="active"><a href="#">Idioma <span class="sr-only">(current)</span></a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <?=$this->flashMessenger()->render('error', array('alert', 'alert-dismissible', 'alert-danger'))?>
    <?=$this->flashMessenger()->render('info', array('alert', 'alert-dismissible','alert-info'))?>
    <?=$this->flashMessenger()->render('default', array('alert', 'alert-dismissible', 'alert-warning'))?>
    <?=$this->flashMessenger()->render('success', array('alert', 'alert-dismissible', 'alert-success'))?>
        
    <div class="container">
			<?php if($this->layout()->tiempoInicial):?>
					<div class="alert-success" role="alert">
					<?php echo $this->layout()->tiempoInicial ?>
					</div>
			<?php endif; ?>
			<?php if($this->layout()->tiempoFinal): ?>
					<div class="alert-success" role="alert">
					<?php echo $this->layout()->tiempoFinal?>
					</div>
			<?php endif; ?>
			<?php if ($this->layout()->tiempoCarga): ?>
					<div class="alert alert-success" role="alert">
					<?php echo $this->layout()->tiempoCarga ?>
					</div>
				<?php endif; ?>
			
            <?= $this->layout()->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
