<?php
if($this->identity()):
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><?= $this->titulo ?></h3>
    </div>
    <div class="panel-body">

        <div class="dropdown">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                Bienvenido <strong>
        
                </strong>
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                <li><a href="<?= $this->url('usuario', ['action' => 'index']) ?>">Administrar Usuarios</a></li>
                <li><a href="<?= $this->url('catalogo', ['action' => 'index']) ?>">Administrar Catalogo</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="<?= $this->url('login', ['action' => 'logout']) ?>">Cerrar sesi&oacute;n</a></li>
            </ul>
        </div>

    </div>
</div>
<?php
else:
    echo "Debe Logearse";
?>
<a href="<?= $this->url('login') ?>">Login</a>
<?php
endif;
?>



