<div class="page-header">
    <h1><?= $this->titulo ?></h1>
</div>
<table class="table" style="width:700px;">
    <thead>
        <tr>
            <th>Module</th>
            <th>Controller</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Modulo Blog &raquo;</td>
            <td>BlogController &raquo;</td>
            <td>index</td>
        </tr>
    </tbody>
</table>


